[workspace]
members = [
    "canon",
    "canon_derive",
    "canon_module",		
    "canon_host",
    "canon_fuzz",
    "canon_host/examples/counter",
    "canon_host/examples/storage",
    "canon_host/examples/panic",				
]
