[workspace]
members = [
    "canon",
    "canon_derive",
    "canon_module",
    "canon_host",
    "canon_fuzz",
]

[patch.crates-io]
canonical = { path = "canon" }
canonical_host = { path = "canon_host" }
canonical_derive = { path = "canon_derive" }
