[package]
name = "canonical"
version = "0.1.0"
authors = ["Kristoffer Ström <kristoffer@dusk.network>"]
edition = "2018"

[dev-dependencies]
canonical_host = { path = "../canon_host" }
canonical_derive = { path = "../canon_derive" }

[features]
hosted = []
host = []
