[package]
name = "canonical"
version = "0.1.0"
authors = ["Kristoffer Ström <kristoffer@dusk.network>"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/dusk-network/canonical"
keywords = ["canon", "serialisation", "no_std", "ffi", "database"]
categories =["Database implementations", "Encoding", "External FFI bindings", "No standard library", "WebAssembly"]
description = "A serialization library built for no_std environments where you want to deal with recursive datastructures,"
license = "MPL-2.0"

[dependencies]
blake2b_simd = { version = "0.3", default-features = false }

[dev-dependencies]
canonical_host = { path = "../canon_host" }
canonical_derive = { path = "../canon_derive" }
canonical_collections = { path = "../canon_collections" }

[features]
hosted = []
host = ["blake2b_simd/std"]
